spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    ru.otus.hw.services: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"