spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true